<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.TestHost" Version="10.0.0" />
    <ProjectReference Include="../../src/AAuth.Events/AAuth.Events.csproj" />
    <ProjectReference Include="../../samples/EventSupport/EventSupport.csproj" />
  </ItemGroup>
</Project>