namespace AAuth.Tests.Api;

internal static class DocumentationSnippetContext
{
    internal const string Imports = """
        using System.Collections.Generic;
        using System.Security.Claims;
        using System.Text;
        using AAuth.Access;
        using AAuth.Person;
        using AAuth.Errors;
        using AAuth.Identifiers;
        using AAuth.Server.CallChaining;
        using AAuth.Server.Challenge;
        using AAuth.Server.Governance;
        using AAuth.Server.Metadata;
        using AAuth.Server.Authorization;
        using AAuth.Events;
        using Microsoft.AspNetCore.Mvc;
        using Microsoft.AspNetCore.Authorization;
        using Microsoft.Extensions.Logging;
        using Concierge;
        using R3AccessServer;
        """;

    internal const string Fields = """
        private string[] args = [];
        private WebApplication app = null!;
        private IServiceCollection services = null!;
        private IServiceProvider serviceProvider = null!;
        private HttpContext context = null!;
        private HttpClient signed = null!, signedHttp = null!, parentSignedClient = null!;
        private HttpContent content = null!;
        private MetadataClient metadataClient = null!;
        private JwksClient jwks = null!, jwksClient = null!;
        private TokenVerifier tokenVerifier = null!, verifier = null!;
        private TokenVerifier.VerifiedToken verifiedAgent = null!, verifiedToken = null!, verifiedUpstream = null!;
        private TokenExchangeClient exchangeClient = null!;
        private AAuthGovernanceClient governance = null!;
        private AgentProviderClient apClient = null!;
        private AccessServerClient accessServerClient = null!;
        private AAuthTokenHolder tokenHolder = null!;
        private ITokenRefresher refresher = null!, tokenRefresher = null!, internalRefresher = null!, externalRefresher = null!;
        private AAuthSigningHandler signingHandler = null!;
        private AAuthEgressPolicy egressPolicy = null!;
        private IJtiStore jtiStore = null!;
        private GovernanceOptions governanceOptions = null!, options = null!;
        private ChallengeOptions challengeOptions = null!;
        private SampleApp.SelfIssuedIdentity identity = null!;
        private EnrollResult enrollment = null!, enrol = null!;
        private AAuthKey agentKey = null!, agentPublicKey = null!, agentSigningKey = null!, agentConfirmationKey = null!, confirmationKey = null!;
        private AAuthKey apKey = null!, apSigningKey = null!, asKey = null!, psKey = null!, psSigningKey = null!, psPublicKey = null!;
        private AAuthKey signingKey = null!, resourceSigningKey = null!, resourcePublicKey = null!, externalKey = null!;
        private AAuthKey conciergeKey = null!, resourceBKey = null!, intermediaryKey = null!, subAgentKey = null!;
        private string agentToken = "held-agent-token", heldAgentToken = "held-agent-token", agentTokenJwt = "held-agent-token";
        private string heldToken = "held-token", preAcquiredToken = "held-token", chainedAuthToken = "held-token", upstreamAuthToken = "held-upstream-token";
        private string upstreamToken = "held-upstream-token", incomingAuthToken = "held-auth-token", subAgentToken = "held-child-token";
        private string resourceTokenJwt = "held-resource-token", resourceTokenString = "held-resource-token", authTokenString = "held-auth-token";
        private string namingJwt = "held-naming-token", eventToken = "held-event-token";
        private string resource = "https://wallet.example", resourceOrigin = "https://trips.example", downstreamResource = "https://calendar.example";
        private string conciergeUrl = "https://concierge.example", concierge = "https://concierge.example", calendarUrl = "https://calendar.example";
        private string intermediaryUrl = "https://concierge.example", intermediaryResourceUrl = "https://concierge.example", downstreamUrl = "https://calendar.example/events";
        private string psIssuer = "https://ps.example", ps = "https://ps.example", asIssuer = "https://as.example", asUrl = "https://as.example";
        private string authenticatedPsIdentifier = "https://ps.example";
        private AgentIssuanceContext issuance = null!;
        private string apUrl = "https://ap.example", agentProvider = "https://ap.example", psTokenEndpoint = "https://ps.example/token";
        private string jwksUrl = "https://ap.example/jwks", kid = "key", ResourceKid = "key", PsKid = "key", AsKid = "key", apKid = "key", apKeyId = "key", conciergeKid = "key";
        private string identifier = "aauth:agent@ap.example", agentIdentifier = "aauth:agent@ap.example", resourceBAgent = "aauth:agent@concierge.example";
        private string intermediaryAgentId = "aauth:agent@concierge.example", parentId = "aauth:parent@ap.example", subId = "aauth:parent+child@ap.example";
        private string scope = "read", mode = "jwt", dwk = "aauth-agent.json", headerS256 = "held-digest", proposalHash = "held-digest";
        private Uri pendingUrl = null!, subscriptionUrl = null!;
        private byte[] approvalBodyBytes = [], payloadBytes = [], subscriptionParameters = [];
        private Dictionary<string, IAAuthKey> signingKeys = [];
        private HashSet<string> trustedAccessServers = [];
        private JsonObject claims = null!, upstreamAct = null!, upstreamActNode = null!, validatedUpstreamAct = null!, parameters = null!;
        private object reservation = null!;
        private PermissionResult cancelBooking = null!;
        private R3Enforcement enforcement = null!;
        private string auditPath = "/configured-private-data/r3-audit.sqlite";
        private ILogger logger = null!;
        private IAgentProviderEventStore durableProviderStore = null!, providerStore = null!;
        private IResourceEventStore durableResourceStore = null!;
        private IAgentEventStore durableAgentStore = null!, agentStore = null!;
        private ResourceSubscription subscription = null!;
        private string agent = "aauth:agent@ap.example", resourceKid = "key", subscribeToken = "held-subscribe-token";
        private Func<string, Task> Surface = null!, SurfaceInteraction = null!;
        private Func<Interaction, CancellationToken, Task> ShowConsentAsync = null!, SurfaceInteractionAsync = null!;
        private Action<string> SurfaceClarification = null!;
        private Func<Task> CancelBookingAsync = null!;
        private Action AddToCalendar = null!;
        private Func<string> GetLatestToken = null!, GetUpstreamToken = null!;
        private Func<HttpContext, PendingStore.Entry, IResult> ReEmitChainedInteraction = null!;
        private Func<HttpContext, Task<IResult>> handler = null!;
        private Func<string, Task<string>> AskUser = null!;
        private Func<string, IReadOnlyList<string>, Task<string>> AskUserToPick = null!;
        private Func<HttpContext, string, Task<IResult>> RunChainAsync = null!;
        private IMissionStore store = null!;
        private IIdentityClaimsAsserter identityAsserter = null!;
        private IAccessPolicy accessPolicy = null!;
        private Func<TokenRefreshContext, CancellationToken, Task<string>> refreshFunc = null!;
        private string assertion = "held-self-jwt";
        private string responseFromAs = "held-auth-token";
        private Task SurfaceToUser(string url) => Task.CompletedTask;
        private CallChainingOptions chainingOptions = null!;
        private IMissionApprover missionApprover = null!;
        private IPermissionDecider permissionDecider = null!;
        private IAuditSink missionAuditSink = null!;
        private IInteractionRelay interactionRelay = null!;
        private Func<InteractionRequest, CancellationToken, Task<bool>> askThroughUserChannel = null!;
        private ISignatureKeyResolver issuerPolicyResolver = null!;
        private Dictionary<string, JsonNode?> heldClaims = [];
        private string directedSubject = "directed-person";
        private Func<JsonObject, bool> validateSubscriptionParameters = null!;
        private TokenExchangeClient originalExchange = null!;
        private string intermediaryResourceToken = "held-resource-token", workerToken = "held-child-token", parentToken = "held-parent-token";
        private AAuthKey parentKey = null!;
        private TokenExchangeRequest consentOptions = null!;
        private HttpClient workerClient = null!;
        private string wallet = "https://wallet.example";
        """;
}